### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by GjermundOstensvig** [Tobhal/HIOF-Models-and-Digital-Twins#15]
After running for a while, the program consistantly throws this error:
```
java.lang.ArrayIndexOutOfBoundsException: Index 25 out of bounds for length 25
        at org.thingml.generated.MQTTDriver.lambda$buildMQTTDriver_behaviorMQTTDriver$1(MQTTDriver.java:435)
        at no.sintef.jasm.Transition.lambda$action$1(Transition.java:24)
        at no.sintef.jasm.AtomicState.handle(AtomicState.java:38)
        at no.sintef.jasm.Region.handle(Region.java:37)
        at no.sintef.jasm.CompositeState.handle(CompositeState.java:77)
        at no.sintef.jasm.Component.run(Component.java:203)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by GjermundOstensvig** [comment]
The issue seems to be with the MQTTDriver
